name: Build & Push

on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  packages: write
  pull-requests: write # Needed to create/update PRs

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run unit tests
        run: pytest -q

  docker:
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref_type == 'branch' && (github.ref_name == 'main' || github.ref_name == 'develop')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v3

      ## Push to ghcr.io
      - name: Login to github
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: github_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          tags: |
            ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ${{ github.ref_name == 'main' && format('ghcr.io/{0}:latest', github.repository) || '' }}
          push: true
          labels: |
            ${{ steps.github_meta.outputs.labels }}

      ## Push to docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            ${{ github.repository }}:sha-${{ github.sha }}
            ${{ github.repository }}:${{ github.ref_name }}
            ${{ github.ref_name == 'main' && format('{0}:latest', github.repository) || '' }}
          labels: |
            ${{ steps.docker_meta.outputs.labels }}
