name: Release Please

on:
  push:
    branches:
      - main


      
permissions:
    packages: write
    pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }}

      # Docker Hub steps
      - name: Log in to Docker Hub
        if: steps.release.outputs.release_created == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull latest image (Docker Hub)
        if: steps.release.outputs.release_created == 'true'
        run: |
          docker pull ${{ github.repository }}:latest

      - name: Tag image with new version (Docker Hub)
        if: steps.release.outputs.release_created == 'true'
        run: |
          docker tag ${{ github.repository }}:latest ${{ github.repository }}:${{ steps.release.outputs.tag_name }}

      - name: Push new version tag (Docker Hub)
        if: steps.release.outputs.release_created == 'true'
        run: |
          docker push ${{ github.repository }}:${{ steps.release.outputs.tag_name }}

      # GHCR steps
      - name: Log in to GHCR
        if: steps.release.outputs.release_created == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest image (GHCR)
        if: steps.release.outputs.release_created == 'true'
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest

      - name: Tag image with new version (GHCR)
        if: steps.release.outputs.release_created == 'true'
        run: |
          docker tag ghcr.io/${{ github.repository }}:latest ghcr.io/${{ github.repository }}:${{ steps.release.outputs.tag_name }}

      - name: Push new version tag (GHCR)
        if: steps.release.outputs.release_created == 'true'
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ steps.release.outputs.tag_name }}
