name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (must start with v, e.g., v1.2.3)'
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  tag-release:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_IMAGE: ${{ github.repository }}
      GHCR_IMAGE: ghcr.io/${{ github.repository }}
      VERSION: ${{ inputs.version }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate version input
        run: |
          if [ -z "$VERSION" ]; then
            echo "VERSION is required"; exit 1;
          fi
          if echo "$VERSION" | grep -Eq '^v[0-9]+(\.[0-9]+){1,2}(-[0-9A-Za-z\.-]+)?$'; then
            echo "Using version: $VERSION"
          else
            echo "Version must start with v and look like v1.2.3"; exit 1;
          fi

      - name: Ensure version tag does not already exist (Docker Hub)
        run: |
          if docker buildx imagetools inspect "$DOCKERHUB_IMAGE:$VERSION" > /dev/null 2>&1; then
            echo "Tag already exists on Docker Hub: $DOCKERHUB_IMAGE:$VERSION";
            exit 1;
          fi

      - name: Ensure version tag does not already exist (GHCR)
        run: |
          if docker buildx imagetools inspect "$GHCR_IMAGE:$VERSION" > /dev/null 2>&1; then
            echo "Tag already exists on GHCR: $GHCR_IMAGE:$VERSION";
            exit 1;
          fi

      - name: Retag multi-arch manifest (Docker Hub)
        run: |
          docker buildx imagetools create --tag "$DOCKERHUB_IMAGE:$VERSION" "$DOCKERHUB_IMAGE:latest"

      - name: Retag multi-arch manifest (GHCR)
        run: |
          docker buildx imagetools create --tag "$GHCR_IMAGE:$VERSION" "$GHCR_IMAGE:latest"
